FROM golang:1.21-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git
COPY go.mod ./
COPY internal ./internal
COPY cmd/api ./cmd/api
RUN go build -o /bin/api ./cmd/api

FROM gcr.io/distroless/base-debian12
USER nonroot:nonroot
COPY --from=builder /bin/api /bin/api
EXPOSE 8080 9101
ENTRYPOINT ["/bin/api"]
