FROM golang:1.21-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git
COPY go.mod ./
COPY internal ./core
COPY cmd/indexer ./cmd/indexer
RUN go build -o /bin/indexer ./cmd/indexer

FROM gcr.io/distroless/base-debian12
USER nonroot:nonroot
COPY --from=builder /bin/indexer /bin/indexer
EXPOSE 9101 9100
ENTRYPOINT ["/bin/indexer"]
